#!/usr/bin/env python3
import os

os.system("sudo pip3 install SpeechRecognition")
os.system("sudo apt-get install flac")
os.system("aplay /usr/share/sounds/alsa/*")
os.system("sudo apt-get update")
os.system("sudo apt-get install espeak")
os.system("sudo pip3 install num2words")
os.system("sudo pip3 install wikipedia")
os.system("sudo pip3 install requests")
os.system("sudo pip3 install beautifulsoup4")
os.system("sudo pip3 install selenium")
os.system("sudo apt-get install firefox-esr")
os.system("sudo apt-get install firefox")
os.system("sudo apt-get install mpg123")
os.system("sudo pip3 install bs4")
os.system("sudo pip3 install lxml")
os.system("wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz")
os.system("tar -xvzf geckodriver-v0.24.0-linux64.tar.gz")
os.system("chmod +x geckodriver")
os.system("sudo mv geckodriver /usr/local/bin/")
os.system("sudo pip3 install opencv-python")
os.system("sudo pip3 install -U scikit-image")
os.system("sudo apt-get install libcblas-dev")
os.system("sudo apt-get install libhdf5-dev")
os.system("sudo apt-get install libhdf5-serial-dev")
os.system("sudo apt-get install libatlas-base-dev")
os.system("sudo apt-get install libjasper-dev")
os.system("sudo apt-get install libqtgui4")
os.system("sudo apt-get install libqt4-test")
os.system("sudo apt install gcc")
os.system("sudo apt-get install automake")
os.system("sudo apt-get update")
os.system("sudo apt-get install libtool")
os.system("sudo apt-get install swig")
os.system("sudo apt-get install python3-setuptools")
os.system("sudo apt-get install python3-dev build-essential")
os.system("sudo apt-get install libtool-bin")
os.system("sudo apt-get install libpulse-dev")
os.system("sudo apt-get install autoconf")
os.system("sudo apt-get install bison")
os.system("sudo pip3 install pocketsphinx")
os.system("sudo apt-get install sox")
os.system("sudo pip3 install deepspeech")
os.system("wget https://github.com/mozilla/DeepSpeech/releases/download/v0.4.1/deepspeech-0.4.1-models.tar.gz")
os.system("tar xvfz deepspeech-0.4.1-models.tar.gz")
